import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { NYOTA_ONE, resolveInitialTenant, type TenantBranding } from "@/lib/tenants";
import { mailClient } from "@/lib/api/client";

interface BrandContextValue {
  tenant: TenantBranding;
}

const BrandContext = createContext<BrandContextValue>({ tenant: NYOTA_ONE });

export function BrandProvider({ children }: { children: ReactNode }) {
  // Lazy init so the first render already uses the correct tenant palette
  // — no flash of the Nyota default while an effect runs post-mount.
  const [tenant, setTenant] = useState<TenantBranding>(() => resolveInitialTenant());

  useEffect(() => {
    // Re-resolve on mount in case SSR fell back to the default.
    const resolved = resolveInitialTenant();
    if (resolved.id !== tenant.id) setTenant(resolved);

    // The gateway is authoritative for branding: it resolves the tenant from
    // the request Host and returns stored branding. Local resolution stays as
    // the instant-paint fallback.
    let cancelled = false;
    mailClient
      .tenantBranding()
      .then((b) => {
        if (cancelled || !b?.id) return;
        setTenant((prev) => ({
          ...prev,
          id: b.id!,
          name: b.name ?? prev.name,
          hostname: b.hostname ?? prev.hostname,
          primary: b.primary ?? prev.primary,
          accent: b.accent ?? prev.accent,
          logoUrl: b.logoUrl ?? prev.logoUrl,
          faviconUrl: b.faviconUrl ?? prev.faviconUrl,
          welcomeMessage: b.welcomeMessage ?? prev.welcomeMessage,
          supportEmail: b.supportEmail ?? prev.supportEmail,
          autoGenerated: false,
        }));
      })
      .catch(() => {
        /* offline or gateway down — keep the locally resolved brand */
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);


  useEffect(() => {
    const root = document.documentElement;
    root.style.setProperty("--primary", tenant.primary);
    root.style.setProperty("--ring", tenant.primary);
    root.style.setProperty("--sidebar-primary", tenant.primary);
    root.style.setProperty("--sidebar-ring", tenant.primary);
    root.style.setProperty("--accent", tenant.accent);
    document.title = `${tenant.name} — Inbox`;
  }, [tenant]);

  const value = useMemo(() => ({ tenant }), [tenant]);
  return <BrandContext.Provider value={value}>{children}</BrandContext.Provider>;
}

export function useTenant() {
  return useContext(BrandContext).tenant;
}
