// Tenant branding — currently in-memory; will be replaced with a DB lookup
// once Lovable Cloud is enabled. Hostname resolves to a tenant.

export interface TenantBranding {
  id: string;
  name: string;
  hostname: string; // matched against window.location.hostname
  logoUrl?: string;
  faviconUrl?: string;
  loginBgUrl?: string;
  welcomeMessage: string;
  primary: string; // oklch(...) value
  accent: string;
  supportEmail?: string;
  autoGenerated?: boolean;
}

// Default = Nyota One. Any hostname that isn't explicitly mapped falls back here.
export const NYOTA_ONE: TenantBranding = {
  id: "nyota",
  name: "Nyota One",
  hostname: "inbox.nyota.one",
  welcomeMessage: "Welcome back to Nyota Inbox.",
  primary: "oklch(0.42 0.18 265)",
  accent: "oklch(0.78 0.15 68)",
  supportEmail: "support@nyota.one",
};

// Demo tenants — replace with DB lookup.
export const TENANTS: TenantBranding[] = [
  NYOTA_ONE,
  {
    id: "acme",
    name: "Acme Corp",
    hostname: "inbox.acme.com",
    welcomeMessage: "Sign in to Acme Mail.",
    primary: "oklch(0.55 0.2 25)",
    accent: "oklch(0.75 0.15 200)",
    supportEmail: "it@acme.com",
  },
  {
    id: "orbit",
    name: "Orbit Labs",
    hostname: "inbox.orbit.io",
    welcomeMessage: "Welcome to Orbit Mail.",
    primary: "oklch(0.5 0.19 155)",
    accent: "oklch(0.78 0.14 90)",
    supportEmail: "help@orbit.io",
  },
];

// Deterministic palette so an unknown inbox.<company>.<tld> host still gets
// a stable, on-brand look on first paint instead of the Nyota default flash.
function hashString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h * 16777619) >>> 0;
  }
  return h;
}

function generateTenantFromHost(host: string): TenantBranding {
  // host like "inbox.company.com" -> company slug "company"
  const parts = host.split(".");
  const slug = (parts.length >= 3 && parts[0] === "inbox" ? parts[1] : parts[0]) || "tenant";
  const name = slug.charAt(0).toUpperCase() + slug.slice(1);
  const h = hashString(slug);
  const hue = h % 360;
  const accentHue = (hue + 140) % 360;
  return {
    id: `auto-${slug}`,
    name,
    hostname: host,
    welcomeMessage: `Sign in to ${name} Mail.`,
    primary: `oklch(0.52 0.18 ${hue})`,
    accent: `oklch(0.78 0.14 ${accentHue})`,
    autoGenerated: true,
  };
}

export function resolveTenantByHost(host: string | undefined | null): TenantBranding {
  if (!host) return NYOTA_ONE;
  const normalized = host.toLowerCase().split(":")[0];
  const registered = TENANTS.find((t) => t.hostname === normalized);
  if (registered) return registered;
  // Any inbox.<something> host gets an auto-branded tenant so onboarding
  // demos work without pre-registering every domain.
  if (normalized.startsWith("inbox.") && normalized.split(".").length >= 3) {
    return generateTenantFromHost(normalized);
  }
  return NYOTA_ONE;
}

// Resolve at module load so the very first render already has the right brand,
// avoiding a flash of the Nyota default palette on other tenant hosts.
export function resolveInitialTenant(): TenantBranding {
  if (typeof window === "undefined") return NYOTA_ONE;
  const params = new URLSearchParams(window.location.search);
  const override = params.get("tenant");
  if (override) {
    const match = TENANTS.find((t) => t.id === override || t.hostname === override);
    if (match) return match;
  }
  return resolveTenantByHost(window.location.hostname);
}
